triggers:
  cron: "@weekly"
#pre_build_script:
#  - apt-get -y install xmlsec1
script:
  - "export POETRY_HOME=/opt/poetry"
  - "python3.9 -m venv $POETRY_HOME"
  - "$POETRY_HOME/bin/pip install -U pip poetry"
  - "$POETRY_HOME/bin/poetry install --with dev,test,coverage,docs --sync"
  - "$POETRY_HOME/bin/poetry run pytest"
  - "$POETRY_HOME/bin/poetry build"
publish_over_ssh:
  - pypi.sunet.se
clean_workspace: true